/* eslint-disable */
// This file is automatically generated. Do not edit.

const BASE_PATH = '/sounds/music';

export const musicMapping = {
  menu: {
    main: `${BASE_PATH}/356_Adventure_Begins.mp3`,
    character: `${BASE_PATH}/3_The_March_of_the_Faithful.mp3`,
    vendors: `${BASE_PATH}/389_Medieval_Market.mp3`,
    dungeons: `${BASE_PATH}/42_Rise_of_the_Ancients.mp3`,
  },
  town: {
    general: [
      `${BASE_PATH}/201_Haven.mp3`,
      `${BASE_PATH}/439_Goodhaven.mp3`,
      `${BASE_PATH}/62_Middle_Earth_Dawn.mp3`,
      `${BASE_PATH}/235_Rainy_Village.mp3`,
      `${BASE_PATH}/397_Homecoming.mp3`,
    ],
    inn: [
      `${BASE_PATH}/23_The_Slaughtered_Ox.mp3`,
      `${BASE_PATH}/342_Tavern_Celebration.mp3`,
      `${BASE_PATH}/407_Viking_Tavern.mp3`,
    ],
    crafting: [
      `${BASE_PATH}/crafting_theme.mp3`,
      `${BASE_PATH}/219_Tinkerers_Workshop.mp3`,
      `${BASE_PATH}/276_Forge_of_Fury.mp3`,
    ],
    enchanter: [
      `${BASE_PATH}/76_Alchemists_Lab.mp3`,
      `${BASE_PATH}/246_Magic_Shoppe.mp3`,
      `${BASE_PATH}/413_Collegium_Magica.mp3`,
    ],
  },
  dungeonThemes: {
    fire: [
      `${BASE_PATH}/100_Volcano.mp3`,
      `${BASE_PATH}/445_Lava_Kings_Lair.mp3`,
      `${BASE_PATH}/373_Infernal_Machine.mp3`,
      `${BASE_PATH}/403_Steel_Foundry.mp3`,
      `${BASE_PATH}/365_Trail_of_Ashes.mp3`,
    ],
    ice: [
      `${BASE_PATH}/31_Frozen_Wastes.mp3`,
      `${BASE_PATH}/55_Ice_Cavern.mp3`,
      `${BASE_PATH}/178_Ice_Throne.mp3`,
      `${BASE_PATH}/296_The_Frozen_Trail.mp3`,
      `${BASE_PATH}/399_Whiteout.mp3`,
      `${BASE_PATH}/183_Sea_of_Moving_Ice.mp3`,
    ],
    nature: [
      `${BASE_PATH}/161_Forest_Day.mp3`,
      `${BASE_PATH}/35_Swamplandia.mp3`,
      `${BASE_PATH}/228_Mushroom_Forest.mp3`,
      `${BASE_PATH}/243_Jungle_Ruins.mp3`,
      `${BASE_PATH}/313_Dusk_of_the_Dryad.mp3`,
      `${BASE_PATH}/91_Elven_Glade.mp3`,
    ],
    shadow: [
      `${BASE_PATH}/10_In_The_Shadows.mp3`,
      `${BASE_PATH}/37_Catacombs.mp3`,
      `${BASE_PATH}/170_The_Underdark.mp3`,
      `${BASE_PATH}/198_Shadowfell.mp3`,
      `${BASE_PATH}/435_The_Undercroft.mp3`,
      `${BASE_PATH}/99_Cavern_of_Lost_Souls.mp3`,
    ],
  },
  dungeonSpecific: {
    dungeon_1: `${BASE_PATH}/49_Goblins_Cave.mp3`,
    dungeon_2: `${BASE_PATH}/400_Whispering_Caverns.mp3`,
    dungeon_4: `${BASE_PATH}/369_Troll_Grotto.mp3`,
    dungeon_9: `${BASE_PATH}/335_Abandoned_Chapel.mp3`,
    dungeon_17: `${BASE_PATH}/299_Necropolis.mp3`,
    dungeon_19: `${BASE_PATH}/31_Frozen_Wastes.mp3`,
    dungeon_21: `${BASE_PATH}/276_Forge_of_Fury.mp3`,
    dungeon_23: `${BASE_PATH}/82_Nightmare.mp3`,
    dungeon_25: `${BASE_PATH}/46_Cathedral.mp3`,
    dungeon_26: `${BASE_PATH}/412_Tomb_Guardians.mp3`,
    dungeon_28: `${BASE_PATH}/432_Lair_of_the_Wyrm.mp3`,
    dungeon_29: `${BASE_PATH}/100_Volcano.mp3`,
    dungeon_33: `${BASE_PATH}/236_Defiled_Temple.mp3`,
    dungeon_38: `${BASE_PATH}/139_Sunken_Temple.mp3`,
    dungeon_39: `${BASE_PATH}/178_Ice_Throne.mp3`,
    dungeon_42: `${BASE_PATH}/139_Sunken_Temple.mp3`,
    dungeon_43: `${BASE_PATH}/146_Floating_Ice_Castle.mp3`,
    dungeon_44: `${BASE_PATH}/438_Red_Sky_Mine.mp3`,
    dungeon_45: `${BASE_PATH}/169_The_Feywild.mp3`,
    dungeon_46: `${BASE_PATH}/238_Mind_Flayer_Chamber.mp3`,
    dungeon_48: `${BASE_PATH}/445_Lava_Kings_Lair.mp3`,
  },
  combat: {
    default: `${BASE_PATH}/72_Monster_Attack.mp3`,
    boss: `${BASE_PATH}/187_Endgame_drake.mp3`,
  }
};
